lang: ru
title: Юрий Матюхин
author: ymatuhin
email: ym@ymatuhin.ru
description: > # this means to ignore newlines until "baseurl:"
  Фронтенд разработчик, веду блог,
  интересуюсь архитектурой приложений,
  дизайном и текстом. Хочу работать на себя
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ymatuhin.ru" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: ymatuhin
logo: /assets/icons/android-chrome-512x512.png
social:
  name: Юрий Матюхин
  links:
    - https://twitter.com/ymatuhin
    - https://github.com/ymatuhin
    - https://vk.com/ymatuhin
    - https://www.facebook.com/ym.ymatuhin

# Build settings
safe: true
paginate: 10
paginate_path: "/archive/:num/"

permalinks: pretty
permalink: /:categories/:title/
sass:
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

